#JavaApp ERP Configuration
#Fri Jul 17 01:25:42 IST 2026
company.email=jsdhameliya1989@gmail.com
company.gstin=BEEPD4909N84653
company.name=DS Engineers
company.phone=9099839193
notifications.enabled=true
notifications.log=17 Jul 2026, 01\:25 \u2014 Signed in successfully.\n17 Jul 2026, 01\:05 \u2014 1 item(s) are at or below their minimum stock level.\n17 Jul 2026, 01\:04 \u2014 29 item(s) were imported or updated.\n17 Jul 2026, 00\:57 \u2014 1 item(s) are at or below their minimum stock level.\n17 Jul 2026, 00\:30 \u2014 1 item(s) are at or below their minimum stock level.\n17 Jul 2026, 00\:29 \u2014 1 item(s) are at or below their minimum stock level.\n17 Jul 2026, 00\:28 \u2014 1 item(s) are at or below their minimum stock level.
smtp.appPassword=jnmg hqgc wfxs ugmz
smtp.email=shailesh.rockstar007@yahoo.com
theme=LIGHT
db.url=jdbc:sqlite:JavaAppERP.db
db.user=
db.password=
smtp.server=smtp.example.com
smtp.port=587
smtp.user=noreply@example.com
smtp.password=secret

